package com.brobot.brobotREST.Brobots.BDM.GameStates;

import com.brobot.brobotREST.Primatives.Enums.GameStateEnum;

public enum GameStateEnumsBDM implements GameStateEnum {
    MAIN_MENU, MAIN_MENU_OPEN,
    ERROR_STATE_BDM, BUTTONS_BDM, ITEMS_BDM,
    WORLD, GO_TO_DORF,
    CAMP_SIDEBAR,
    POSTEN, POSTEN_CLOSE_BESTATIGUNG, POSTEN_GEBAUDE, POSTEN_OFFNEN_BESTATIGUNG,
        ERGEBNIS_DES_POSTEN_HANDELS, POSTEN_VERWALTEN, ARBEITER_ENTSENDEN,
    REFINERY,
    GARTEN,
    KOMMANDOPOSTEN,
    LAGER,
    VIEHSTALL,
    CAMP, CAMP_OPEN_BESTATIGUNG, CAMP_CLOSE_BESTATIGUNG,
    QUEST_BESTATIGUNG,
    WELT_SAMMELN, WELT_SAMMELN_OPEN, WELT_SAMMELN_ARBEITER_WAHLEN,
    WORKERS, WORK_ABGESCHLOSSEN,
    ARENA_KAMPF, ARENA_EMPFANG,
    GILDE,
    SCHWARZGEIST_EMPFANG, GEIST_FUTTERN, SCHWARZGEIST_QUESTS,
    LEXIKON,
    TALENT,
    MAIL, EVENT_REWARDS, LOGIN_REWARDS, PEARL_SHOP, TASKS,
    PETS
}
